import { ContactForm } from "@/components/contact-form";

export default function Home() {
  return (
    <div className="site-shell">
      <header className="nav"><a className="logo" href="#top">ME<span>.</span></a><nav><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="availability" href="#contact"><i /> Available for select projects</a></header>
      <main id="top">
        <section className="hero"><p className="eyebrow">Independent designer + developer <span>Based in New York / working everywhere</span></p><h1>I make digital things<br /><em>feel human.</em></h1><div className="hero-bottom"><p>I&apos;m Mara, a product designer and developer obsessed with the space where clarity meets character. I help good ideas become experiences people remember.</p><a className="circle-link" href="#work" aria-label="Scroll to selected work">↓</a><span className="issue">EST. 2018<br />ISSUE No. 07</span></div></section>
        <section className="work" id="work"><div className="section-heading"><p className="eyebrow">01 / Selected work</p><p className="count">(04)</p></div><div className="projects"><article className="project project-wide"><div className="project-visual visual-coral"><span className="visual-mark">◒</span><span className="visual-label">quietly<br />powerful</span></div><div className="project-meta"><div><h2>Kindred</h2><p>A new kind of community platform for people who care deeply about where they live.</p></div><span>Brand / Product / 2024</span></div></article><article className="project project-offset"><div className="project-visual visual-blue"><span className="orb">✳</span><span className="visual-label">make room<br />for wonder</span></div><div className="project-meta"><div><h2>Field Notes</h2><p>An editorial tool for collecting the small things that make a day.</p></div><span>Product / Development / 2023</span></div></article><article className="project"><div className="project-visual visual-yellow"><span className="grid-mark">＋</span><span className="visual-label">good work<br />takes time</span></div><div className="project-meta"><div><h2>Common Ground</h2><p>Reframing the annual report as a living, breathing story.</p></div><span>Editorial / 2023</span></div></article><article className="project project-offset"><div className="project-visual visual-ink"><span className="star-mark">✦</span><span className="visual-label">a little<br />more light</span></div><div className="project-meta"><div><h2>Solstice</h2><p>A slow-fashion label with a bright point of view.</p></div><span>Identity / E-commerce / 2022</span></div></article></div></section>
        <section className="about" id="about"><div className="section-heading"><p className="eyebrow">02 / A little about me</p></div><div className="about-grid"><h2>Thoughtful by default.<br /><em>Curious by nature.</em></h2><div><p>I work across strategy, design, and code to build products that earn their place in people&apos;s lives. No black boxes, no handoffs over the wall, no pretending the details don&apos;t matter.</p><p>When I&apos;m away from my desk, you&apos;ll find me looking for the best bookstore in town, making a very specific playlist, or taking the long way home.</p><a className="text-link" href="mailto:hello@maraellis.studio">More about me <span>↗</span></a></div></div></section>
        <section className="contact" id="contact"><div><p className="eyebrow">03 / Start a conversation</p><h2>Have a good<br /><em>one?</em> Let&apos;s talk.</h2><a href="mailto:hello@maraellis.studio" className="email">hello@maraellis.studio ↗</a></div><ContactForm /></section>
      </main><footer><span>© 2025 Mara Ellis</span><span>Made with care & curiosity</span><a href="#top">Back to top ↑</a></footer>
    </div>
  );
}
