"use client";

import { motion } from "framer-motion";
import { ContactForm } from "@/components/contact-form";

const projects = [
  { title: "Kindred", status: "Shipped", type: "Product platform", year: "2024", description: "A new kind of community platform for people who care deeply about where they live.", skills: ["Next.js", "TypeScript", "Prisma"], image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=85", github: "https://github.com/", live: "https://kindred.example.com" },
  { title: "Field Notes", status: "Shipped", type: "Editorial tool", year: "2023", description: "A calm, tactile workspace for collecting the small things that make a day.", skills: ["React", "Node.js", "SQLite"], image: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=1200&q=85", github: "https://github.com/", live: "https://fieldnotes.example.com" },
  { title: "Common Ground", status: "Shipped", type: "Annual report", year: "2023", description: "Reframing the annual report as a living story about people, progress, and place.", skills: ["UX strategy", "Motion", "CMS"], image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85", github: "https://github.com/", live: "https://commonground.example.com" },
  { title: "Solstice", status: "In development", type: "E-commerce identity", year: "2022", description: "A slow-fashion label with a bright point of view and a considered online shop.", skills: ["Brand", "Shopify", "Art direction"], image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85", github: "https://github.com/", live: "https://solstice.example.com" },
];

const skills = { "Primary language": ["TypeScript", "JavaScript", "Python"], "Front-end": ["Next.js", "React", "Tailwind CSS", "Framer Motion"], "Back-end": ["Node.js", "Prisma", "REST APIs", "SQLite / PostgreSQL"], "DevOps & tools": ["GitHub Actions", "Vercel", "Docker", "Figma"] };
const experiences = [
  { period: "2023 — now", role: "Independent designer + developer", place: "Mara Ellis Studio", copy: "Partnering with thoughtful teams to shape brands, products, and digital experiences from the first sketch to the final deploy." },
  { period: "2020 — 2023", role: "Senior product designer", place: "Northstar Labs · New York", copy: "Led product direction across a family of tools used by more than 40,000 creative professionals." },
  { period: "2017 — 2020", role: "Designer / front-end developer", place: "Common Practice · Brooklyn", copy: "Built visual identities and accessible websites for culture, education, and mission-driven organizations." },
];
const reveal = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: 0.7, ease: "easeOut" as const } } };

export default function Home() {
  return (
    <div className="site-shell">
      <motion.header className="nav" initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}><a className="nav-email" href="mailto:hello@maraellis.studio">hello@maraellis.studio</a><a className="logo" href="#top">ME<span>.</span></a><nav><a href="#work">Work</a><a href="#skills">Skills</a><a href="#experience">Experience</a><a href="#about">About</a><a href="#contact">Contact</a></nav></motion.header>
      <main id="top">
        <motion.section className="hero" initial="hidden" animate="show" variants={reveal}><div className="hero-copy"><p className="eyebrow">Profile / 01 <span>Tokyo / everywhere</span></p><div className="hero-portrait"><p className="hero-name-back">Matuso<br />Takahashi</p><img src="/avatar.png" alt="Matuso Takahashi" /></div><p className="hero-name">Matuso Takahashi</p></div><div className="hero-about"><p className="eyebrow">About me <span>Independent designer + developer</span></p><h1>I make digital things<br /><em>feel human.</em></h1><p className="hero-description">I design and build clear, characterful experiences for people and teams doing meaningful work. My practice sits between thoughtful product design, expressive visual systems, and reliable code.</p><a className="hero-cta" href="#about">More about me <span>↓</span></a></div></motion.section>
        <motion.section className="section-block work" id="work" initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.12 }} variants={reveal}><div className="section-heading"><div><p className="eyebrow">01 / Selected work</p><h2>Things I&apos;ve helped<br /><em>bring to life.</em></h2></div><p className="count">(04 projects)</p></div><div className="projects">{projects.map((project, index) => <motion.article className="project-card" key={project.title} whileHover={{ y: -8 }} transition={{ duration: 0.25 }}><div className="project-image" style={{ backgroundImage: `url(${project.image})` }}><span className="project-index">0{index + 1}</span><div className="project-links"><a href={project.github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={project.live} target="_blank" rel="noreferrer">Live site ↗</a></div></div><div className="project-meta"><div><p className="project-type">{project.type} / {project.year} / <span className={project.status === "In development" ? "status-active" : "status-shipped"}>{project.status}</span></p><h3>{project.title}</h3><p>{project.description}</p></div><div className="skill-tags">{project.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></motion.article>)}</div></motion.section>
        <motion.section className="section-block skills" id="skills" initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.15 }} variants={reveal}><div className="section-heading"><div><p className="eyebrow">02 / The toolkit</p><h2>Good ideas need<br /><em>good tools.</em></h2></div></div><div className="skills-grid">{Object.entries(skills).map(([group, items], index) => <div className="skill-group" key={group}><p className="skill-number">0{index + 1}</p><h3>{group}</h3><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></div>)}</div></motion.section>
        <motion.section className="section-block experience" id="experience" initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.15 }} variants={reveal}><div className="section-heading"><div><p className="eyebrow">03 / Experience</p><h2>A few places<br /><em>I&apos;ve been.</em></h2></div></div><div className="experience-list">{experiences.map((experience) => <article className="experience-row" key={experience.period}><p className="experience-period">{experience.period}</p><div><h3>{experience.role}</h3><p className="experience-place">{experience.place}</p><p className="experience-copy">{experience.copy}</p></div><span className="row-arrow">↗</span></article>)}</div></motion.section>
        <motion.section className="section-block about" id="about" initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.2 }} variants={reveal}><div className="section-heading"><p className="eyebrow">04 / About</p></div><div className="about-grid"><h2>Thoughtful by default.<br /><em>Curious by nature.</em></h2><div><p>I work across strategy, design, and code to make products that earn their place in people&apos;s lives. No black boxes, no handoffs over the wall, no pretending the details don&apos;t matter.</p><p>When I&apos;m away from my desk, you&apos;ll find me looking for the best bookstore in town, making a very specific playlist, or taking the long way home.</p><div className="contact-details"><a href="mailto:hello@maraellis.studio">hello@maraellis.studio ↗</a><span>Brooklyn, New York<br />Available worldwide</span></div></div></div></motion.section>
        <motion.section className="contact" id="contact" initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.2 }} variants={reveal}><div><p className="eyebrow">05 / Start a conversation</p><h2>Have a good<br /><em>one?</em> Let&apos;s talk.</h2><p className="contact-intro">Have a project, a question, or a good book recommendation? I&apos;d love to hear from you.</p></div><ContactForm /></motion.section>
      </main><footer><span>© 2025 Mara Ellis</span><span>Made with care & curiosity</span><a href="#top">Back to top ↑</a></footer>
    </div>
  );
}
